<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="common" tests="1" failures="1" errors="0" skipped="0" time="11.919" timestamp="2018-11-08T11:19:01">
  <properties></properties>
  <testcase classname="com.example" name="test1" time="11.919">
    <failure>
      <![CDATA[Exception in thread "main" java.lang.RuntimeException: A test exception
  at com.example.stacktrace.StackTraceExample.methodB(StackTraceExample.java:13)
  at com.example.stacktrace.StackTraceExample.methodA(StackTraceExample.java:9)
  at com.example.stacktrace.StackTraceExample.main(StackTraceExample.java:5)]]>
    </failure>
  </testcase>
</testsuite>
