<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="common" tests="4" failures="2" errors="0" skipped="2" time="47.676" timestamp="2018-11-08T11:19:01">
  <properties></properties>
  <testcase classname="com.example" name="test1" time="11.919">
    <failure>
      <![CDATA[Exception in thread "main" java.lang.RuntimeException: A test exception
  at com.example.stacktrace.StackTraceExample.methodB(StackTraceExample.java:13)
  at com.example.stacktrace.StackTraceExample.methodA(StackTraceExample.java:9)
  at com.example.stacktrace.StackTraceExample.main(StackTraceExample.java:5)]]>
    </failure>
  </testcase>
  <testcase classname="com.example" name="test2" time="11.919">
    <skipped></skipped>
  </testcase>
  <testcase classname="com.example" name="test2" time="11.919">
    <failure></failure>
  </testcase>
  <testcase classname="com.example" name="test3" time="11.919">
    <skipped>
      <![CDATA[Exception in thread "main" java.lang.RuntimeException: A test exception
  at com.example.stacktrace.StackTraceExample.methodB(StackTraceExample.java:13)
  at com.example.stacktrace.StackTraceExample.methodA(StackTraceExample.java:9)
  at com.example.stacktrace.StackTraceExample.main(StackTraceExample.java:5)]]>
    </skipped>
  </testcase>
</testsuite>
